### ISSUE TITLE
Would you be interested in publishing this through npm?

### ISSUE THREAD

**Issue by jrhorn424** [mauriciosoares/pin.js#19]
I'd be happy to help you do this. It seems the [name may not be available](https://www.npmjs.com/package/pinjs), but perhaps we can come up with an alternative?

**Comment by mauriciosoares** [comment]
Hi @jrhorn424, I'm not supporting this package anymore... it's probably full of bugs as well, since I haven't maintained it in a couple of years...  :|

**Comment by jrhorn424** [comment]
Ok, understood. Thank you @mauriciosoares!
