### ISSUE TITLE
test on mobile

### ISSUE THREAD

**Issue by mauriciosoares** [mauriciosoares/pin.js#6]
this plugin should work smoothly on mobile devices

**Comment by mauriciosoares** [comment]
Based on some research and tests, it works smoothly on Android/Chrome and IOS/Safari

It bugs on IOS/Chrome, because IOS has a inbuilt rule that it freezes the repaint/reflow part of the browser whenever the user is scrolling the bar, the javascript runs, but you can only see when the user stops scrolling it :/

But since it works smoothly on IOS/Safari, this plugin can be used to build Phonegap apps, :)

**Comment by LorenzoPirondini** [comment]
Hi, what was the IOS version you tested on? 
Before IOS8 the javascript was "paused" while scrolling on the iphone
more details:
http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/

also on what version of android did you test it?

**Comment by mauriciosoares** [comment]
Actually I tested on IOS8 - Safari, previously it will probably not work properly :/

And on android I tested on version 5.0.1 Lollipop. On older versions it will probably not work properly as well...
